home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("", views.index, name="index"),
    path("services/", views.services, name="services"),
    path("pricing/", views.pricing, name="pricing"),
    path("contact/", views.contact, name="contact"),
    path("about/", views.about, name="about"),
    path("careers/", views.careers, name="careers"),
    path("apply/", views.apply, name="apply"),
]

morrison/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include("home.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Contact(models.Model):
    time = models.DateField(default=timezone.now)
    username = models.CharField(max_length=64)
    phone = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    message = models.CharField(max_length=1000)


class Pricing(models.Model):
    time = models.DateField(default=timezone.now)
    fname = models.CharField(max_length=64)
    lname = models.CharField(max_length=64)
    cname = models.CharField(max_length=64)
    phone = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    checks = models.CharField(max_length=30)
    message = models.CharField(max_length=1000)

class Jobs(models.Model):
    time = models.DateField(default=timezone.now)
    username = models.CharField(max_length=64)
    phone = models.CharField(max_length=64)
    email = models.CharField(max_length=64)
    role = models.CharField(max_length=100)
    message = models.CharField(max_length=1000)
    cv = models.CharField(max_length=1000)

home/views.py
from django.shortcuts import render
from home.models import Contact, Pricing, Jobs
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.core.files.storage import FileSystemStorage

import os.path

# Create your views here.


def index(request):
    if request.method == "POST":
        uname = request.POST['username']
        phone = request.POST['phone']
        email = request.POST['email']
        msg = request.POST['message']

        rec = Contact(username=uname, phone=phone, email=email, message=msg)
        rec.save()
        messages.success(request, 'Your message has been received. We will be in touch with you shortly.')
    # return HttpResponseRedirect(reverse('home:index'))
        ref = request.META['HTTP_REFERER']
        refx = ref[-8:-1]
        if(refx == "contact"):
            return render(request, "home/contact.html")
        elif (refx == "careers"):
            return render(request, "home/careers.html")
        else:
            return render(request, "home/index.html")
    return render(request, "home/index.html")


def services(request):
    return render(request, "home/services.html")


def pricing(request):
    if request.method == "POST":
        fname = request.POST['fname']
        lname = request.POST['lname']
        cname = request.POST['cname']
        phone = request.POST['phone']
        email = request.POST['email']
        checks = request.POST['drop']
        msg = request.POST['message']

        rec = Pricing(fname=fname, lname=lname, cname=cname,
                      phone=phone, email=email, checks=checks, message=msg)
        rec.save()
        messages.success(
            request, 'Your Offer has been received. We will be in touch shortly.')
        return HttpResponseRedirect(reverse('home:pricing'))
        # print(fname, lname, cname, phone, email, checks, msg)
    return render(request, "home/pricing.html")



def contact(request):
    return render(request, "home/contact.html")


def about(request):
    return render(request, "home/about.html")


def careers(request):
    return render(request, "home/careers.html")


def apply(request):
    if request.method == "POST":
        uploaded_file = request.FILES['cv']
        fs = FileSystemStorage()
        ext = os.path.splitext(uploaded_file.name)[1]
        valid_exts = ['.pdf', '.doc', '.docx']
        if not ext.lower() in valid_exts:
            messages.success(
            request, 'Please upload valid PDF or Word file!')
            return HttpResponseRedirect(reverse('home:apply'))
        
        name = fs.save(uploaded_file.name, uploaded_file)
        
        url = fs.url(name)
        fname = request.POST['fname']
        phone = request.POST['phone']
        email = request.POST['email']
        rolee = request.POST['rolee']
        msg = request.POST['message']

        rec = Jobs(username=fname, phone=phone, email=email, role=rolee, message=msg, cv=url)
        rec.save()
        messages.success(
            request, 'Your Application has been received. We will be in touch with you shortly!')
        return HttpResponseRedirect(reverse('home:apply'))
        # print(fname, lname, cname, phone, email, checks, msg)
    
    return render(request, "home/apply.html")

home/templates/home/about.html
{% extends "home/layout.html"%} {% load static%} {% block body %}

<section id="banner_parallax" class="inner_page_banner slide_banner1">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="full">
          <div class="slide_cont">
            <h2>About us</h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end header -->
<!-- section -->
<section class="layout_padding padding_top_0">
  <div class="container col-sm-12 col-xs-12">
    <div class="imf_icon">
      <img src="{% static 'home/images/about.png'%}" alt="#" />
    </div>

    <p class="lead" style="text-align: justify;">
      We guarantee efficiency and proper verification processes to ensure your
      new hire is what they say they are and go above and beyond to discover the
      undiscover of our competitors.
    </p>
    <h4>Why Use Us for This Purpose</h4>
    <p class="lead" style="text-align: justify;">
      Our experts have decades of experience in security and Identity checks and
      their expertise gives them the leverage to handle the process with
      uttermost proficiency. Unlike our competitors, we give companies the
      option to have a choice of either doing a complete background check or
      partial aspect of the candidate for which the fees are dependent on your
      choice. You are guaranteed the highest and most secured protection to your
      Information and data as our experts are licensed Cyber Security experts
      governed under the rules of HIPAA -HITECH NAPA, Military Intelligence and
      many more that restrict us from keeping data unsafe. We don't just scan
      your candidate for generic Information as commonly done , we proceed
      further by making sure every contact on the resume is reached and cross
      checked with the prospective companies , as well as checking the real
      contacts of the previously worked companies against the contacts on the
      resumes . Last but not the least we save you time and money to ensure your
      new hire is more than qualified for the vacancy you hope to fill. And we
      do this by diving deeper into the candidate’s background before assuring
      you of their Identity.
    </p>
  </div>
</section>
<!-- end section -->
<!-- section -->
<section class="layout_padding gradiant_bg cross_layout">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <div class="full text_align_center white_fonts">
          <div class="heading_main center_head_border heading_style_1">
            <h2>Easy <span>Steps</span></h2>
          </div>
        </div>
      </div>
    </div>
    <div class="row step_section">
      <div class="offset-xl-1 col-xl-10 col-md-12">
        <div class="row">
          <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
            <div class="step_blog arrow_right_step">
              <div class="step_inner">
                <i class="fa fa-diamond"></i><br />
                <p>Go app store</p>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
            <div class="step_blog">
              <div class="step_inner">
                <i class="fa fa-user"></i><br />
                <p>Create an Account</p>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
            <div class="step_blog">
              <div class="step_inner">
                <i class="fa fa-download"></i><br />
                <p>Download & Install</p>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
            <div class="step_blog">
              <div class="step_inner">
                <i class="fa fa-thumbs-up"></i><br />
                <p>Enjoy & Rate us!</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock%}

home/templates/home/apply.html
{% extends "home/layout.html"%} {% load static%} {% block body %}

<section id="banner_parallax" class="inner_page_banner slide_banner1">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="full">
                    <div class="slide_cont">
                        <h2>Apply Here</h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end header -->
<!-- section -->
<section class="layout_padding">
    <div class="container">
        <div class="row">
            <div class="full">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="full text_align_center">
                            <div class="heading_main center_head_border heading_style_1">
                                <h2>Apply for your desired job</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="row margin_bottom_30">
                <!-- featured image -->
                <div class="col-md-6 wow fadeInLeft" data-wow-delay="0.5" data-wow-duration="1s">
                    <div class="full">
                        <div class="center">
                            <img class="low-res" src="{%static 'home/images/apply.png'%}" alt="#" />
                        </div>
                    </div>
                </div>
                <!-- end featured image -->
                <!-- featured cont -->
                <div class="col-md-6 cont_theme_blog">
                    <div class="full gradiant_bg">
                        <div class="contact_form white_heading_border" id="order-now">
                            <div class=" ">
                                <div class="full_heading heading_main heading_style_1 white_fonts">
                                    <h2>Enter Morrison <span></span></h2>
                                </div>
                                <p>
                                    An Excellent future awaits you.
                                </p>
                                <div class="form_contact">
                                    <!-- form -->
                                    <form action="{% url 'home:apply' %}" method="post" enctype="multipart/form-data">
                                        {% csrf_token %}
                                        <fieldset>
                                            <div class="field">
                                                <input type="text" name="fname" placeholder="Your Full Name " required=" " />
                                            </div>

                                            <div class="field">
                                                <input type="text " name="phone" placeholder="Your phone Number " required=" " />
                                            </div>
                                            <div class="field">
                                                <input type="email " name="email" placeholder=" Your Email Address " required=" " />
                                            </div>

                                            <div class="field">
                                                <select class="form-control" style="margin-top: 8px;" name="rolee">
                          <option value="None Selected" disabled selected hidden
                            >Applied Role</option
                          >
                          <option value="Risk Management Manager">Risk Management Manager</option>
                          <option value="Consumer Services Analyst">Consumer Services Analyst</option>
                        </select>
                                            </div>
                                            <div class="field">
                                                <span class="cv-tagline">Attach your Resume</span>
                                            </div>
                                            <div class="field">
                                                <input name="cv" type="file" class="form-control" id="validatedCustomFile" required style="
                        line-height: 1.5;
                        padding-top: 8px;
                    ">
                                            </div>
                                            <div class="field">
                                                <textarea name="message" placeholder="Any Message" required=" "></textarea>
                                            </div>
                                            <div class="field">
                                                <button class="field_bt">Send</button>
                                            </div>
                                        </fieldset>
                                    </form>
                                    <!-- end form -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- end featured cont -->
            </div>
        </div>
    </div>
</section>
<!-- end section -->
<!-- section -->
<section class="layout_padding gradiant_bg cross_layout">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="full text_align_center white_fonts">
                    <div class="heading_main center_head_border heading_style_1">
                        <h2>Our Services</h2>
                    </div>
                </div>
            </div>
        </div>
        <div class="row app-features">
            <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
                <div class="information_blogs special">
                    <div class="imf_icon">
                        <img src="{% static 'home/images/id-card.png'%}" alt="# " />
                    </div>
                    <div class="imf_head">
                        <h3>Background Check</h3>
                        <a class="white_bt bt_main bt_special" href="# ">Know More</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
                <div class="information_blogs special">
                    <div class="imf_icon">
                        <img src="{% static 'home/images/rental.png'%}" alt="# " />
                    </div>
                    <div class="imf_head">
                        <h3>Rental History</h3>
                        <a class="white_bt bt_main bt_special" href="# ">Know More</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
                <div class="information_blogs special">
                    <div class="imf_icon">
                        <img src="{% static 'home/images/banking.png'%}" alt="# " />
                    </div>
                    <div class="imf_head">
                        <h3>Banking & Credit</h3>
                        <a class="white_bt bt_main bt_special" href="# ">Know More</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 col-xs-12">
                <div class="information_blogs special">
                    <div class="imf_icon">
                        <img src="{% static 'home/images/folder.png'%}" alt="# " />
                    </div>
                    <div class="imf_head">
                        <h3 style="font-size: 18px;">ID & Driving Records</h3>
                        <a class="white_bt bt_main bt_special" href="# ">Know More</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- end section -->
{% endblock%}

home/templates/home/contact.html
{% extends "home/layout.html"%} {% load static%} {% block body %}

<!-- section -->
<section class="contact_section">
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-6" style="padding: 0;">
        <div class="full">
          <div id="map"></div>
        </div>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6" style="padding: 0;">
        <div class="full">
          <div class="contact_form white_heading_border">
            <div class="contact_form_inner">
              <div
                class="full_heading white_fonts heading_main heading_style_1"
              >
                <h2>Contact <span>us</span></h2>
              </div>
              <p>
                Sed ut perspiciatis unde omnis iste natus error sit voluptatem
                accusantium doloremque laudantium, totam rem aperiam, eaque ipsa
                quae ab illo inventore veritatis et quasi architecto beatae
                vitae dicta sunt explicabo.
              </p>
              <div class="form_contact">
                <!-- form -->
                <form action="{% url 'home:index' %}" method="post">
                  {% csrf_token %}
                  <fieldset>
                    <div class="field">
                      <input
                        type="text"
                        name="username"
                        placeholder="Your name "
                        required=" "
                      />
                    </div>
                    <div class="field">
                      <input
                        type="text"
                        name="phone"
                        placeholder="Your phone "
                        required=" "
                      />
                    </div>
                    <div class="field">
                      <input
                        type="email"
                        name="email"
                        placeholder="Email "
                        required=" "
                      />
                    </div>
                    <div class="field">
                      <textarea
                        name="message"
                        placeholder="Enter Message"
                        required=" "
                      ></textarea>
                    </div>
                    <div class="field">
                      <button class="field_bt">Send</button>
                    </div>
                  </fieldset>
                </form>
                <!-- end form -->
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock%}

home/templates/home/layout.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Morrison Records Bureau - Home</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- site icons -->
    <link rel="icon" href="{% static 'home/images/fevicon/fevicon.png' %}" type="image/png" />
    <!-- bootstrap css -->
    <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}" />
    <!-- site css -->
    <link rel="stylesheet" href="{% static 'home/css/style.css'%}" />
    <!-- responsive css -->
    <link rel="stylesheet" href="{% static 'home/css/responsive.css' %}" />
    <!-- colors css -->
    <link rel="stylesheet" href="{% static 'home/css/colors.css'%}" />
    <!-- wow animation css -->
    <link rel="stylesheet" href="{% static 'home/css/animate.css'%}" />
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
</head>

<body id="default_theme" class="home_page1">

    <!-- Modal -->
    <div class="modal fade" id="testmo" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="testmo">ALERT!</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
                </div>
                <div class="modal-body" style=" color: black; text-align: center; padding: 3rem;">
                    {% if messages %} {% for message in messages %} {{message}} {% endfor %} {% endif %}
                </div>
                <!-- <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div> -->
            </div>
        </div>
    </div>






    <header class="header header_style1">
        <div class="container">
            <div class="row">
                <div class="col-md-9 col-lg-10">
                    <div class="logo">
                        <a href="{%url 'home:index' %}"><img src="{% static 'home/images/logo.jpg'%}" alt="#" /></a>
                    </div>
                    <div class="main_menu float-right">
                        <div class="menu">
                            <ul class="clearfix">
                                <li class="active"><a href="{%  url 'home:index' %}">Home</a></li>
                                <li class="dropdown"><a href="{% url 'home:services'%}">Services</a>
                                    <div class="dropdown-content">
                                        <a href="{% url 'home:services'%}#bg-check">Background Checks</a>
                                        <a href="{% url 'home:services'%}#banking">Banking History</a>
                                        <a href="{% url 'home:services'%}#rental-history">Rental History</a>
                                        <a href="{% url 'home:services'%}#acc-report">Accident Reports</a>
                                        <a href="{% url 'home:services'%}#acc-report">Comming Soon!</a>
                                    </div>
                                </li>
                                <!-- <li><a href="{% url 'home:pricing'%}">Pricing</a></li> -->
                                <li><a href="{% url 'home:contact'%}">Contact</a>
                                </li>
                                <li><a href="{% url 'home:about'%}">About</a></li>
                                <li><a href="{% url 'home:careers'%}">Careers</a></li>

                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-lg-2">
                    <div class="right_bt"><a class="bt_main" href="{% url 'home:pricing'%}">Get a Quote</a> </div>
                </div>
            </div>
        </div>
    </header>



    {% block body%} {% endblock%}

    <!-- footer -->
    <footer class="footer_style_2 ">
        <div class="footer_top ">
            <div class="container ">
                <div class="row ">
                    <div class="col-xs-12 col-sm-5 col-md-6 col-lg-3 margin_bottom_30 ">
                        <div class="full width_9 " style="margin-bottom:25px; ">
                            <a href="index.html "><img class="img-responsive " width="200 " src="{% static 'home/images/logo.jpg'%}" alt="# "></a>
                        </div>
                        <div class="full width_9 ">

                        </div>
                        <div class="full width_9 ">

                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-7 col-md-6 col-lg-4 margin_bottom_30 ">
                        <div class="full ">
                            <div class="footer_blog_2 width_9 ">
                                <h3></h3>
                                <p>at Morrison Records, we guarantee efficiency and proper verification processes to ensure your new hire is what they say they are and go above and beyond to discover the undiscover of our competitors.</p>
                                <p>You are guaranteed the highest and most secured protection to your Information and data as our experts are licensed Cyber Security experts governed under the rules of HIPAA -HITECH NAPA, Military Intelligence and many more
                                    that restrict us from keeping data unsafe.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-2 margin_bottom_30 ">
                        <div class="full ">
                            <div class="footer_blog_2 ">
                                <h3>Social</h3>
                            </div>
                        </div>
                        <div class="full ">
                            <ul class="footer-links ">
                                <li><a href="# "><i class="fa fa-facebook "></i> 256 Likes</a></li>
                                <li><a href="# "><i class="fa fa-github "></i> 57+ Projects</a></li>
                                <li><a href="# "><i class="fa fa-twitter "></i> 1,258 Followers</a></li>
                                <li><a href="# "><i class="fa fa-pinterest "></i> 2538+ Pins</a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 margin_bottom_30 ">
                        <div class="full ">
                            <div class="footer_blog_2 width_9 ">
                                <h3>Navigation</h3>
                            </div>
                            <div class="blog_post_footer ">
                                <a class="white_bt bt_main bt_special " href="{% url 'home:services'%}">Services</a> </div>
                            <div class="blog_post_footer ">
                                <a class="white_bt bt_main bt_special " href="{% url 'home:pricing' %}">Pricing</a> </div>
                            <div class="blog_post_footer ">
                                <a class="white_bt bt_main bt_special " href="{% url 'home:about' %}">About Us </a> </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        </div>
        </div>
        <!-- footer bottom -->
        <div class="footer_bottom ">
            <p>Copyright &copy; 2020 <strong>Morrison Records. </strong> All rights reserved.</p>
        </div>
    </footer>
    <!-- end footer -->
    <!--=========== js section ===========-->
    <!-- jQuery (necessary for Bootstrap's JavaScript) -->
    <!-- <script>
        setTimeout(function() {
            if ($('#msg').length > 0) {
                $('#msg').fadeOut()
            }
        }, 6000)
    </script> -->
    <script src="{% static 'home/js/jquery.min.js'%}"></script>
    <script src="{% static 'home/js/popper.min.js'%}"></script>
    <script src="{% static 'home/js/bootstrap.min.js'%}"></script>
    <!-- wow animation -->
    <script src="{% static 'home/js/wow.js'%}"></script>
    <!-- custom js -->
    <script src="{% static 'home/js/custom.js'%}"></script>
    <!-- google map js -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCAY0sS2ebpk9KpxwifEZ2PFm_52flP13g&callback=initMap "></script>
    <!-- end google map js -->

    {% if messages %} {% for message in messages %}
    <script type="text/javascript">
        $(document).ready(function() {
            $("#testmo").modal('show');
        });
    </script>
    {% endfor %} {% endif %}

</body>

</html>

home/templates/home/msg.html
{% if messages %}
    {% for message in messages %}
    <div class="gradiant_bg alert alert-{{ message.tags}} m-2" id="msg" role="alert" style="
    min-height: 2px;
    color: white;
    text-align: center;
    text-transform: capitalize;
    padding: 0 !important;
    margin: 0 !important;
    font-size: 15px;">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}